name: pylint and other code quality checks

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        uses: Gr1N/setup-poetry@v8
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install
      - name: pylint
        run: poetry run poe pylint
      - name: mypy
        run: poetry run poe mypy
      - name: black
        run: poetry run poe black-check
      - name: isort
        run: poetry run poe isort-check
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        uses: Gr1N/setup-poetry@v8
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install
      - name: pytest
        run: poetry run poe test
      - name: coverage
        run: poetry run poe coverage
      - name: store coverage
        uses: orgoro/coverage@v3
        with:
          coverageFile: ./cov.xml
          token: ${{ secrets.GITHUB_TOKEN }}
