name: Generate docs using pdoc3 and deploy content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.10"
      - name: Install poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install dependencies
        env:
          POETRY_VIRTUALENVS_CREATE: "0"
        run: poetry install
      - name: Build docs
        run: poe docs
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: ".public/mongorm"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
